### ISSUE TITLE
Template Function Implementation Questions

### ISSUE THREAD

**Issue by dreadingervr** [jd3dgiant/CodingInterviewLearning#1]
https://github.com/jd3dgiant/CodingInterviewLearning/blob/b869622fd9ab5ebe19de97ebd835f3a1b14dafa5/LinkedList/LinkedList/LinkedList.h#L19

https://github.com/jd3dgiant/CodingInterviewLearning/blob/b869622fd9ab5ebe19de97ebd835f3a1b14dafa5/LinkedList/LinkedList/LinkedList.h#L45

Curious as to why one is implemented inside the class and one is implemented outside the class?

**Comment by jd3dgiant** [comment]
I believe when I wrote this, I was running into template linking issues and so I was experimenting with what works and what does not. I will need to refactor it all before my next commit.
