### ISSUE TITLE
Why not store this as '0' instead of decimal 48? The compiler knows that '0' is a character version of zero which is stored as 48 internally. It's more human readable as '0' instead of thinking about "What's 48 in ascii?".

### ISSUE THREAD

**Issue by dreadingervr** [jd3dgiant/CodingInterviewLearning#2]
https://github.com/jd3dgiant/CodingInterviewLearning/blob/03f061c75cdb00aca7c257a09c2982b9aebb6045/Strings/TypeConverter.h#L7

**Comment by jd3dgiant** [comment]
Mentally for me, seeing an int being assigned to a character confuses my brain even though it is implicitly converted. Changing this to "const int LOWESTASCIINUMBERVALUE = '0';"
